### PR TITLE
Rails5 with sprockets

### PR DESCRIPTION
**Pull request by mariochavez**
Refactored to Railtie and added support for Sprockets 3.0+

This branch has support for Rails 5 and uses the assets pipeline to compile
`elm` files based on PR #4 from @botandrose

### CODE REVIEW

**Comment by juanibiapina** [comment]
This doesn't seem to work with Rails 4. I followed the exact steps on the new README and got this:

```
couldn't find file 'Hello' with type 'application/javascript'
```

on the line:

```
//= require Hello
```

**Comment by mariochavez** [comment]
@juanibiapina what version of sprockets are you using with Rails 4?

I'll give it a try.
Also this gem is lacking of test, that is something that I would like to add sooner.

**Comment by juanibiapina** [comment]
sprockets 3.6.0

**Comment by mariochavez** [comment]
Sample project for Rails 4 and Elm 0.17 https://github.com/mariochavez/rails4-and-elm-017

**Comment by ujh** [comment]
This works for me with a Rails 4 app and it's considerably faster than `master`. 👍

**Comment by mmccullar** [comment]
What is causing this not to be merged into master? Would love to use Rails 5 with Elm!

**Comment by lsimoneau** [comment]
Is there anything I can do to help get this merged?

**Comment by lsimoneau** [comment]
I've rolled these commits into #12 which I'll be merging shortly, so closing this one. Let me know if there's anything else outstanding.

**Pull request closed without merging**
